spring:
  cloud:
    discovery:
      enabled: false
      client:
        health-indicator:
          enabled: false  
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: vets-service
          uri: http://vets-service.apps.internal:8080
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: http://visits-service.apps.internal:8080
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://customers-service.apps.internal:8080
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
