server:
  port: 8080
spring:
  datasource:
    platform: mysql
    initialization-mode: always
    url: ${vcap.services.mysql.credentials.jdbcUrl:jdbc:mysql://localhost:3306/petclinic?useSSL=false}
    username: ${vcap.services.mysql.credentials.username:root}
    password: ${vcap.services.mysql.credentials.password:petclinic}

#Wavefront
management:
  metrics:
    export:
      wavefront:
        uri: http://192.168.8.20
        api-token: ${VCAP_SERVICES_WAVEFRONT_TOKEN_CREDENTIALS_TOKEN}
