spring.cloud.kubernetes.discovery.enabled: true
spring.cloud.discovery.enabled: false
wavefront:
  application:
    name: pet-clinic-k8s
  freemium-account: true
management:
  metrics:
    export:
      wavefront:
        enabled: false
