server:
  port: 8080
spring:
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    platform: mysql
    initialization-mode: always
    url: ${vcap.services.mysql.credentials.jdbcUrl:jdbc:mysql://localhost:3306/petclinic?useSSL=false}
    username: ${vcap.services.mysql.credentials.username:root}
    password: ${vcap.services.mysql.credentials.password:petclinic}

#Wavefront
# management:
#   metrics:
#     export:
#       wavefront:
#         uri: http://192.168.8.20
#         api-token: 9d735838
