spring:
  datasource:
    url: ${vcap.services.mysql.credentials.jdbcUrl}
    username: ${vcap.services.mysql.credentials.username}
    password: ${vcap.services.mysql.credentials.password}
    testOnBorrow: true
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    initialization-mode: ALWAYS
  cloud:
    discovery:
      enabled: false
      
