server:
  port: 8080
#Credentials are defined per microservice
spring:
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    platform: mysql
    initialization-mode: always
  cloud:
    services:
      registrationMethod: direct

management:
  metrics:
    export:
      wavefront:
        uri: http://${vcap.services.wavefront.credentials.hostname}:${vcap.services.wavefront.credentials.port}
        #api-token: ${vcap.services.wavefront.credentials.api-token}

wavefront:
  application:
    name: todo-application-tas4vms
  freemium-account: false #change to true if needed...
