spring.cloud.kubernetes.discovery.enabled: true
spring.cloud.discovery.enabled: true
server:
  port: 8080
wavefront:
  application:
    name: pet-clinic-k8s
  freemium-account: false
management:
  metrics:
    export:
      wavefront:
        enabled: false
