spring:
  datasource:
    url: ${vcap.services.customers-db.credentials.jdbcUrl}&statementInterceptors=brave.mysql.TracingStatementInterceptor&zipkinServiceName=customers-db
    username: ${vcap.services.customers-db.credentials.username:root}
    password: ${vcap.services.customers-db.credentials.password:petclinic}
