spring:
  datasource:
    url: ${vcap.services.vets-db.credentials.jdbcUrl}&statementInterceptors=brave.mysql.TracingStatementInterceptor&zipkinServiceName=vets-db
    username: ${vcap.services.vets-db.credentials.username}
    password: ${vcap.services.vets-db.credentials.password}
