spring:
  datasource:
    url: ${vcap.services.visits-db.credentials.jdbcUrl:jdbc:mysql://localhost:3306/petclinic?useSSL=false}
    username: ${vcap.services.visits-db.credentials.username:root}
    password: ${vcap.services.visits-db.credentials.password:petclinic}
